"""
SQLAlchemy models for authentication.
"""
from sqlalchemy import Boolean, Column, Integer, String, DateTime, Text, ForeignKey
from sqlalchemy.ext.declarative import declarative_base
from datetime import datetime

Base = declarative_base()


class User(Base):
    """User model for authentication."""
    
    __tablename__ = "users"
    
    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, index=True, nullable=False)
    username = Column(String, unique=True, index=True, nullable=False)
    hashed_password = Column(String, nullable=False)
    is_active = Column(Boolean, default=True)
    is_superuser = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    def __repr__(self):
        return f"<User(id={self.id}, username={self.username}, email={self.email})>"


class AdminUser(Base):
    __tablename__ = "admin_users"
    id = Column(Integer, primary_key=True, index=True)
    employee_id = Column(String, unique=True, index=True, nullable=False)
    employee_name = Column(String, nullable=False)
    designation = Column(String, nullable=False)
    department = Column(String, nullable=False)
    email_id = Column(String, unique=True, index=True, nullable=False)
    password_hash = Column(String, nullable=False)
    role = Column(String, nullable=False)  # Admin, Reviewer, Lead Engineer, Senior Engineer, Engineer, GET, Read Only
    status = Column(String, default="active")  # active, disabled
    created_date = Column(DateTime, default=datetime.utcnow)
    last_login = Column(DateTime, nullable=True)


class DatasheetApproval(Base):
    __tablename__ = "datasheet_approval"
    id = Column(Integer, primary_key=True, index=True)
    tag_number = Column(String, nullable=False)
    instrument_type = Column(String, nullable=False)
    approved_by = Column(String, nullable=False)
    employee_id = Column(String, nullable=False)
    role = Column(String, nullable=False)
    date = Column(String, nullable=False)
    time_log = Column(String, nullable=False)


class VendorSelectionLog(Base):
    __tablename__ = "vendor_selection_log"
    id = Column(Integer, primary_key=True, index=True)
    tag_number = Column(String, nullable=False)
    vendor = Column(String, nullable=False)
    model = Column(String, nullable=False)
    match_percentage = Column(Integer, nullable=False)
    selected_by = Column(String, nullable=False)
    employee_id = Column(String, nullable=False)
    date = Column(String, nullable=False)
    time = Column(String, nullable=False)


class Employee(Base):
    """Full employee profile — tblemployees."""
    __tablename__ = "tblemployees"
    id = Column(Integer, primary_key=True, index=True)
    employee_id = Column(String, unique=True, index=True, nullable=False)
    employee_name = Column(String, nullable=False)
    designation = Column(String, nullable=False)
    department = Column(String, nullable=False)
    email_id = Column(String, unique=True, index=True, nullable=False)
    phone = Column(String, nullable=True)
    role = Column(String, nullable=False)
    # self-referencing: employee_id of the reporting authority
    reporting_authority_id = Column(String, nullable=True)
    status = Column(String, default="active")   # active | inactive
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, nullable=True)


class Notification(Base):
    """Per-employee notifications generated by system events."""
    __tablename__ = "notifications"
    id = Column(Integer, primary_key=True, index=True)
    recipient_employee_id = Column(String, nullable=False, index=True)
    title = Column(String, nullable=False)
    body = Column(String, nullable=False)
    # approval_submitted | approved | rejected | system
    notif_type = Column(String, nullable=False, default="system")
    related_request_id = Column(Integer, nullable=True)   # approval_requests.id
    is_read = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)


class ApprovalRequest(Base):
    """Raised by a junior/engineer for Lead Engineer review before proceeding."""
    __tablename__ = "approval_requests"
    id = Column(Integer, primary_key=True, index=True)
    request_type = Column(String, nullable=False)        # "spec" | "coversheet"
    tag_numbers = Column(Text, nullable=True)            # JSON array string
    instrument_type = Column(String, nullable=True)
    payload_json = Column(Text, nullable=True)           # JSON: specs or coversheet summary
    submitted_by_name = Column(String, nullable=False)
    submitted_by_id = Column(String, nullable=False)     # submitter's employee ID (informational)
    submitter_notes = Column(String, nullable=True)
    status = Column(String, default="pending")           # pending | approved | rejected
    reviewed_by_name = Column(String, nullable=True)
    reviewed_by_id = Column(String, nullable=True)
    reviewed_role = Column(String, nullable=True)
    review_notes = Column(String, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, nullable=True)
